services:
  vue-dist:
    image: nginx:alpine
    container_name: aos-web-9101
    ports:
      - "9101:80"
    volumes:
      # Map โฟลเดอร์ dist จากเครื่องไปยัง path ของ nginx ใน container
      - ./dist:/usr/share/nginx/html:ro
      # (Option) ถ้ามีไฟล์ nginx.conf เพื่อจัดการ routing
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro