server {
    listen 80 ssl;
    server_name spd-demo.dtc.co.th;

    ssl_certificate /etc/letsencrypt/live/spd-demo.dtc.co.th/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/spd-demo.dtc.co.th/privkey.pem;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html =404;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}